In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
#Task 1

In [ ]:
data = pd.Series(['Iran','Iraq', 'Syria','Lebanon','Jordan']);
data

0       Iran
1       Iraq
2      Syria
3    Lebanon
4     Jordan
dtype: object

In [ ]:
data1= pd.Series(data,
index=['Iran', 'Iraq', 'Syria', 'Lebanon', 'Jordan'])
data


Iran          Iran
Iraq          Iraq
Syria        Syria
Lebanon    Lebanon
Jordan      Jordan
dtype: object

In [ ]:
Height = [120,130]
data = pd.Series(Height, index=['Male', 'Female'])
data


Male      120
Female    130
dtype: int64

In [ ]:
data = {'Name' : ['Majeed','Fahad','Javeria','Rehan','Shees'],
        'Age': [22,23,26,20,21],
        'Major': ['DS', 'AI', 'CS','AI','CS']}
data1 = pd.DataFrame(data,index=['S1','S2','S3','S4','S5'])      
data1


,Name,Age,Major
S1,Majeed,22,DS
S2,Fahad,23,AI
S3,Javeria,26,CS
S4,Rehan,20,AI
S5,Shees,21,CS


In [ ]:
print("___Sales Revenue of Four Different Products_____")
data = {'Computers' :[23,56,78,90,23,100],
        'TV' :[23,56,78,90,23,100],
        'LCD' :[23,56,78,90,23,100],
        'Laptop' :[23,56,78,90,23,100]
        }
data1 = pd.DataFrame(data, index=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'])
data1

___Sales Revenue of Four Different Products_____


,Computers,TV,LCD,Laptop
Jan,23,23,23,23
Feb,56,56,56,56
Mar,78,78,78,78
Apr,90,90,90,90
May,23,23,23,23
Jun,100,100,100,100


In [ ]:
#Task 2

In [ ]:
data = {'Name' : ['Majeed','Fahad','Javeria','Rehan','Shees','Muneeb'],
        'Age': [22,23,26,20,21,45],
        }
data1 = pd.DataFrame(data,index=['S1','S2','S3','S4','S5','S6'])   
s3 = data1.iloc[2]
s3 


Name    Javeria
Age          26
Name: S3, dtype: object

In [ ]:
grade = {'Math' : [34,56,77],
        'Physics': [22,23,26],
        'Chemistry': [56,78,90],
        }
data1 = pd.DataFrame(grade,index=['S1','S2','S3']) 
data1.loc['S2','Physics']

23

In [ ]:
Games = {'Game1':[1,2,1,0],
         'Game2':[0,2,1,0],
         'Game3':[1,1,2,0],
         'Game4':[3,2,0,0],
         'Game5':[4,0,0,0],
}

data = pd.DataFrame(Games,index=['P1', 'P2','P3', 'P4'])
score = data.iloc[0:3]
print(score)
print("_____________________")
a = data.loc['P3']
a

    Game1  Game2  Game3  Game4  Game5
P1      1      0      1      3      4
P2      2      2      1      2      0
P3      1      1      2      0      0
_____________________


Game1    1
Game2    1
Game3    2
Game4    0
Game5    0
Name: P3, dtype: int64

In [ ]:
#Task 3

In [ ]:
Height = [120,130,140,144,120,195]
data = pd.Series(Height, index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6'])
a = data.iloc[3]
a

144

In [ ]:
grade = {'Math' : [34,56,77],
        'Physics': [22,23,26],
        'Chemistry': [56,78,90],
        }
data1 = pd.DataFrame(grade,index=['S1','S2','S3']) 
data1.loc['S3','Chemistry']

90

In [ ]:
Revenue = [100000,120000,130000,39999,400000,345670,23405,23456,90888,109999,12345,12345]
data = pd.DataFrame(Revenue,index=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
Six_months = data.iloc[0:6]
print("Revenu of First Six Months")
print(Six_months)
nov = data.loc['Nov']
print("Revenu of Nov",nov)

Revenu of First Six Months
          0
Jan  100000
Feb  120000
Mar  130000
Apr   39999
May  400000
Jun  345670
Revenu of Nov 0    12345
Name: Nov, dtype: int64


In [ ]:
#Task 4

In [ ]:
array = np.random.randint(0,10,5)
sqrt= np.sqrt(array)
sqrt

array([0.        , 2.        , 1.        , 2.23606798, 1.73205081])

In [ ]:
array = np.random.uniform(-1, 1, 3)
exp= np.exp(array)
exp

array([2.31214117, 0.83487396, 0.62536572])

In [ ]:
array1 = np.random.randint(0, 10, 3)
array2 = np.random.randint(0, 10, 3)
add = np.add(array1, array2)
mul = np.multiply(add, 5)
mul

array([10, 55, 50])

In [ ]:
array = np.random.randint(0, 10, 6)
array2 = np.sort(array)
array2


array([0, 3, 6, 7, 8, 9])

In [ ]:
arr = np.random.randint(0, 100, 10)
mean_arr = np.mean(arr)
std_arr = np.std(arr)
print("Mean:", mean_arr)
print("Standard deviation:", std_arr)


Mean: 32.5
Standard deviation: 27.807373122968663


In [ ]:
#Task 5

In [ ]:
data = pd.DataFrame({'C1': [1, 2, 3, np.nan, 5], 'C2': [6, 7, 8, np.nan, 10], 'C3': [11, 12, 13, 14, 15]})
Value = data.isna()
print(data)
Value


    C1    C2  C3
0  1.0   6.0  11
1  2.0   7.0  12
2  3.0   8.0  13
3  NaN   NaN  14
4  5.0  10.0  15


,C1,C2,C3
0,False,False,False
1,False,False,False
2,False,False,False
3,True,True,False
4,False,False,False


In [ ]:
data = pd.DataFrame({'C1': [1, 2, 3], 'C2': [4, np.nan, 6], 'C3': [7, 8, np.nan], 'D': [10, 11, 12]})
data1 = data.dropna()
data


,C1,C2,C3,D
0,1,4.0,7.0,10
1,2,NaN,8.0,11
2,3,6.0,NaN,12


In [109]:
data = pd.DataFrame({'C1': [1, 2, 3, 4, 5, 6], 'C2': [7, np.nan, 9, np.nan, 11, 12]})
data['C2'] = data['C2'].fillna(data['C2'].mean())
data


,C1,C2
0,1,7.00
1,2,9.75
2,3,9.00
3,4,9.75
4,5,11.00
5,6,12.00
